import myCover from "./../assets/monstera.jpg";

export const plantList = [
  {
    name: "monstera",
    category: "classique",
    id: "1ed",
    isSpecialOffer: true,
    water: 3,
    light: 1,
    cover: myCover,
  },
  {
    name: "ficus lyrata",
    category: "classique",
    id: "2ab",
    isSpecialOffer: true,
    water: 2,
    light: 2,
    cover: myCover,
  },
  {
    name: "pothos argenté",
    category: "classique",
    id: "3sd",
    isSpecialOffer: false,
    water: 1,
    light: 3,
    cover: myCover,
  },
  {
    name: "yucca",
    category: "classique",
    id: "4kk",
    isSpecialOffer: false,
    water: 1,
    light: 1,
    cover: myCover,
  },
  {
    name: "olivier",
    category: "extérieur",
    id: "5pl",
    isSpecialOffer: false,
    water: 1,
    light: 2,
    cover: myCover,
  },
  {
    name: "géranium",
    category: "extérieur",
    id: "6uo",
    isSpecialOffer: false,
    water: 3,
    light: 2,
    cover: myCover,
  },
  {
    name: "basilique",
    category: "extérieur",
    id: "7ie",
    isSpecialOffer: false,
    water: 2,
    light: 3,
    cover: myCover,
  },
  {
    name: "aloe",
    category: "plante grasse",
    id: "8fp",
    isSpecialOffer: false,
    water: 1,
    light: 2,
    cover: myCover,
  },
  {
    name: "succulente",
    category: "plante grasse",
    id: "9vn",
    isSpecialOffer: false,
    water: 2,
    light: 1,
    cover: myCover,
  },
];
